hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
hookfuncion(print, warm)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')
os.sleep(12)
print('cc me may beo')
print('ngu nhu cho')
print('cc me may beo')
print('ngu nhu cho')


